ExpediaGroup/insights-explorer

packages/backend/src/lib/backends/github.sync.ts
This will allow full-text search across all (text-based) files in an Insight.
=> feat: Index text-based files in an Insight

packages/frontend/src/components/file-viewer/file-viewer.tsx
Fixes issues with certain file types that the browser wants to display rather than download as a file.
=> fix: Add the download attribute in the FileViewer

packages/backend/src/lib/backends/github.sync.ts, packages/frontend/src/pages/insight-editor/insight-editor.tsx
Removed lines were previously used to detect templates via tags, which has since been replaced by item types.
=> refactor: Remove deprecated tag code

packages/backend/src/lib/backends/github.sync.ts, packages/backend/src/models/tasks.ts, packages/backend/src/resolvers/insight.resolver.ts
Occasionally the GitHub API will return an old value for `updatedAt` if we sync too quickly after pushing a change.  This change overrides that value whenever we sync after publishing, and uses the current timestamp rather than the GitHub API value.
=> fix: Ensure `updatedAt` is current when publishing changes

.eslintrc.yml, packages/backend/.eslintrc.yml, packages/backend/src/index.ts, packages/backend/src/lib/storage.ts, packages/backend/src/server.ts, packages/convertbot/src/controllers/convert.v1.ts, packages/convertbot/src/controllers/home.v1.ts, packages/convertbot/src/conversions.ts, packages/convertbot/src/index.ts, packages/convertbot/src/lib/convertbot.ts, packages/convertbot/src/server.ts, packages/models/src/indexed/indexed-insight-file.ts, packages/models/src/indexed/indexed-insight-user.ts, packages/models/src/indexed/indexed-insight.ts, packages/models/src/indexed/indexed-repository-person.ts, packages/models/src/indexed/indexed-repository.ts, packages/shared/src/logger.ts, packages/shared/src/search.ts, packages/shared/src/storage.ts, packages/slackbot/src/app.ts, packages/slackbot/src/lib/iex.ts, packages/slackbot/src/lib/unfurls.ts, packages/slackbot/src/server.ts
Added ESLint rule `@typescript-eslint/consistent-type-imports` and fixed all occurrences.
Disabled for `backend` package because TypeGraphQL requires type metadata in order to generate the GraphQL schema correctly.
=> refactor: Prefer consistent type imports

.github/workflows/publish-docker.yaml, .github/workflows/release.yaml
This will help address issues where the release completes but the docker publish fails and we cannot rerun it.
=> chore(workflow): Split release and publish into separate workflows

packages/frontend/src/components/insight-connection-card/components/compact-insight-card/compact-insight-card.tsx, packages/frontend/src/components/insight-connection-card/components/square-insight-card/square-insight-card.tsx, packages/frontend/src/components/insight-list/components/insight-list-skeleton/insight-list-skeleton.tsx, packages/frontend/src/components/insight-list/insight-list.tsx
This PR improves the mobile-friendliness of the Search results when using either the compact layout or the square layout.
**Before**, tags cluttered each result and the title was truncated to accommodate.
**After**, tags are hidden below `md` breakpoint, and limited to the first 5 days above
**Before**, the square boxes scaled down slightly at smaller breakpoints and the wrapping container would turn into a single column if there wasn't room for a 2nd column.  The Insight cards didn't size to fit the column, leaving a lot of extra whitespace.
**After**, below the `sm` breakpoint, it turns into a single column and the Insight cards scale to fit the width of the screen.
=> fix: Mobile-responsive square & compact Insight cards

package.json
Fixes docker build errors due to missing `prune:production` scripts in some of the packages.
=> chore(workflow): Ignore missing `prune:production` scripts

packages/frontend/src/pages/settings-page/components/github-settings/github-settings.tsx
GitHub recently updated the format for personal access tokens: 
https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/
This PR updates the front-end validation on the user's GitHub Integration page
=> fix: Update GitHub personal access token validation pattern

packages/frontend/src/components/link/link.tsx
Fixes the following error when using Link as the target of another component, e.g. `<Button as={Link}>`
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```
=> fix: Fix ref issues with `Link` component

packages/frontend/src/components/markdown-container/chakra-ui-renderer.tsx, packages/frontend/src/components/markdown-container/markdown-container.tsx, packages/frontend/src/components/markdown-editor/markdown-editor.tsx, packages/frontend/src/components/markdown-split-editor/markdown-split-editor.tsx, packages/frontend/src/pages/admin-page/components/news-admin/components/news-item/news-item.tsx, packages/frontend/src/pages/main-page/components/header/components/news-drawer/components/news-item/news-item.tsx
This PR adds an experimental feature to be able to scroll the Markdown editor and the Markdown preview containers independently, and adding the functionality to synchronize the scroll position from the editor to the preview based on the position of the Markdown component.
=> feat: Add checkbox to enable/disable scroll sync on markdown editor

packages/frontend/src/pages/main-page/components/header/components/news-drawer/components/news-item/news-item.tsx
This PR fixes the list component rendered from the custom renderer on the news-item.
=> fix: Add list components to the news-item customComponents renderer

packages/backend/schema.gql, packages/backend/src/lib/backends/github.sync.ts, packages/backend/src/lib/git-instance.ts, packages/backend/src/models/draft.ts, packages/backend/src/models/insight.ts, packages/backend/src/services/insight.service.ts, packages/backend/src/services/user.service.ts, packages/frontend/src/pages/insight-editor/components/insight-metadata-editor/insight-authors.tsx, packages/frontend/src/pages/insight-editor/components/insight-metadata-editor/insight-metadata-editor.tsx, packages/frontend/src/shared/useInsight.ts, packages/frontend/src/urql.ts, packages/models/src/indexed/indexed-insight-config.ts, packages/models/src/indexed/indexed-insight.ts
This change adds two optional YAML configs, `authors` and `excludedAuthors`. These properties modify the default sync behavior of extracting authors from the git repository.
Both properties can be modified in the Insight Editor UI, under an _Advanced_ section.
- `authors`: Contains a list of one or more email addresses that should be used exclusively as the authors of the Insight.  These emails will be linked to IEX users where possible.
- `excludedAuthors`: Contains a list of one or more email addresses to exclude from the auto-generated list of authors.  Useful if someone has made a change on an Insight, but shouldn't be considered an author (e.g. an Admin)
=> feat: Manually specify authors for an Insight

packages/frontend/src/components/markdown-editor/markdown-editor.tsx, packages/frontend/src/components/markdown-split-editor/markdown-split-editor.tsx
This PR fixes an issue with the Markdown Editor when on responsive style it hides the editor from the view. 
This also hides the Scroll Sync checkbox when the Split Editor is not showing both the Editor and Preview.
Original:
Changes:
=> Fix markdown editor UI issues

packages/frontend/src/components/settings-sidebar/settings-sidebar.tsx, packages/frontend/src/pages/admin-page/admin-page.tsx
This PR improves the mobile-responsive design of the Admin page so components can be shown correctly.
Note: The fix is also related to changes from #547
=> fix: Mobile-responsive Admin Page

packages/frontend/src/components/alert/alert.tsx, packages/frontend/src/pages/error-page/error-page.tsx, packages/frontend/src/pages/insight-editor/insight-draft-switcher.tsx, packages/frontend/src/pages/main-page/components/user-health-check/user-health-check.tsx
This PR improves the mobile-responsive design of the Error pages and alerts so components can be shown correctly.
**Insight Error Page**
**User Error Page**
**Default Error Page**
**Alerts**
=> fix: Mobile-friendly Error pages and Alerts

packages/shared/src/search.ts, packages/shared/test/search.test.ts
Previously, Insights could be included in the results due to a `filter` match like `itemType: insight`, even if they didn't match any search terms.  This resulted in a score of `0.0`, but these documents would still appear in the search page.
This change adds the `minimum_should_match` field to the SearchMatch and SearchPhrase terms.  It will ensure that matching documents match at least one of the `should` clauses.  Searches without any `should` clauses (e.g. #tag) won't be affected.
=> fix: Update Insight search to exclude non-matching documents

packages/frontend/src/components/markdown-container/iex-markdown-schema.ts, packages/frontend/src/shared/remark/remark-iex.ts
`width` and `height` attributes were being converted to `w`/`h` for no benefit, as both forms work in Chakra-UI.
The rehype-sanitize schema still contains `w` and `h` since they are convenient shortcuts.
=> refactor: Remove unnecessary use of `w`/`h` attributes

packages/frontend/src/pages/insight-editor/insight-draft-switcher.tsx
This PR improves the mobile-responsive design of the Insight Draft Switcher so components can be shown correctly.
The new version at the left vs the old version at the right.
=> fix: Mobile-friendly Insight Draft Switcher

packages/backend/indices/iex-webhooks.json, packages/backend/src/controllers/webhook.v1.ts
Updates the Elasticsearch mapping for the `iex-webhooks` index, and excluded some unneeded fields from being included.  This change reduces the number of fields created, because dynamic mapping creates unnecessary keyword mappings for text types.
=> fix: Update Webhooks mapping

packages/frontend/src/components/markdown-container/chakra-ui-renderer.tsx, packages/frontend/src/components/markdown-container/markdown-container.css, packages/frontend/src/components/markdown-container/markdown-container.tsx
Markdown styles were lost due to a missing class attribute.
Also refactored one style out of CSS and into JSX.
=> fix: Fix missing Markdown styles

packages/frontend/src/components/file-viewer/file-viewer.tsx, packages/frontend/src/shared/use-scroll-to-location.ts
A new hook, `useScrollToLocation()`, automatically detects anchor links and scrolls them into view when the target element appears.  This solves the problem of opening a deeplink to a specific anchor in a Markdown document, which is rendered asynchronously.
The hook has been added to the FileViewer, so it applies to any Insights, Markdown help page, etc.
=> fix: Fix anchor links to dynamic content (e.g. Markdown headings)

packages/convertbot/README.md, packages/convertbot/src/conversions.ts, packages/convertbot/src/lib/convertbot.ts
The PPTX->PDF conversion now includes a step to convert the PDF into PNGs (per slide).  These images are uploaded alongside the converted PDF, with a naming convention of `presentation.pptx-%d.png`
=> feat(convertbot): Convert pptx files into individual slide PNGs

packages/backend/schema.gql, packages/backend/src/models/user.ts, packages/backend/src/resolvers/user.resolver.ts, packages/backend/src/services/user.service.ts, packages/frontend/src/components/insight-list/insight-list.tsx, packages/frontend/src/pages/profile-page/components/user-profile/components/profile-comment-card/profile-comment-card.tsx, packages/frontend/src/pages/profile-page/components/user-profile/components/user-comments/user-comments.tsx, packages/frontend/src/pages/profile-page/components/user-profile/user-profile.tsx, packages/frontend/src/shared/useUser.ts
=> feat: Add Comments tab to User Profile

packages/backend/src/lib/elasticsearch.ts, packages/backend/src/resolvers/user.resolver.ts, packages/backend/src/services/user.service.ts, packages/frontend/src/pages/profile-page/profile-page.tsx
Previously, the `authoredInsights` and `likedInsights` resolvers would trigger Elasticsearch queries which retrieved entire Insight documents, including the contents of all Insight files.  This is obviously a huge hit to performance and network traffic, especially since the Profile page doesn't request that information in the GraphQL query.
To address this, the requested GraphQL fields are being passed down to the Elasticsearch query as the `_source` argument.  Elasticsearch now only returns the requested fields, reducing the traffic and latency.
=> fix: Optimize Elasticsearch queries for the user profile

packages/frontend/src/components/markdown-split-editor/markdown-split-editor.tsx
This PR addresses the fix where the Scroll Sync checkbox on the Insight Split Editor was required to be checked in order to save news on the News Admin page.
=> fix: Fix Scroll Sync checkbox on News Admin page

packages/backend/src/lib/git-instance.ts, packages/frontend/src/components/file-browser/components/editable-controls/editable-controls.tsx, packages/frontend/src/components/file-browser/file-browser.tsx, packages/frontend/src/pages/insight-editor/components/insight-editor-sidebar/insight-editor-sidebar.tsx, packages/frontend/src/pages/insight-editor/components/insight-editor-sidebar/sidebar-files.tsx, packages/frontend/src/theme.ts
This change replaces the file upload drop target in the Insight Editor with the ability to upload to the root folder or any subfolder.  There is a new Upload button for each folder; it appears on subfolders when hovering over them.  Alternately, each folder (including the root) is a drop target and files can be dragged and dropped into the browser
.
=> feat: Allow uploading files to subfolders via button or drag-n-drop

package-lock.json, packages/frontend/package.json, packages/frontend/src/components/file-browser/components/editable-controls/editable-controls.tsx, packages/frontend/src/components/file-browser/file-browser.tsx, packages/frontend/src/pages/insight-editor/components/insight-editor-sidebar/insight-editor-sidebar.tsx, packages/frontend/src/pages/insight-editor/components/insight-editor-sidebar/sidebar-files.tsx, packages/frontend/src/shared/file-tree.ts, packages/frontend/src/shared/use-file-picker.ts
This commit updates the Insight Editor sidebar to support the following features:
- Moving files between various folders via drag and drop
- Drag and drop file(s) from the computer directly into a folder
- Upload files into a folder via an Upload button
The latter two features are not new, but have been rewritten using `react-dnd`.  This avoids conflicts from having both `react-dropzone` and `react-dnd` wired to the same drop targets.
These features work for the root folder as well as any subfolders or nested subfolders.
This PR also includes a few small UX changes uncovered while developing this feature.
=> feat: Reorganize Insight Files via drag and drop

packages/frontend/src/pages/insight-editor/insight-editor.tsx
When changing a template on the Insight editor the team field will be overwritten and left empty even if the user has a team assigned from their profile.
=> fix: Fix template change overwriting team field

packages/frontend/src/components/user-tag/user-tag.tsx
This PR fixes the alignment from the UserTag component on the user name and admin icon.
=> fix: Fix misaligned text and icon on User Tag

packages/backend/src/lib/backends/github.ts
This error is caused by passing the Pino logger to the GitHub octokit library.
More details here: https://github.com/pinojs/pino/issues/545
=> fix: Fix `this[writeSym] is not a function` error

packages/backend/src/lib/backends/base.sync.ts, packages/backend/src/lib/backends/github.sync.ts
The `repositoryData` field contains details needed to trigger a sync for an Insight, but previously this value was not updated, even if the Insight repository was renamed.  This continued to work thanks to GitHub's redirect functionality, but broke the previous Insight detection to avoid re-publishing unmodified files.
This change updates the repositoryData field with every successful sync.
=> fix: Update `repositoryData` field when syncing Insights

packages/frontend/src/components/activity-view/activity-view.tsx, packages/frontend/src/pages/activity-page/components/activity-search-bar/activity-search-bar.tsx, packages/frontend/src/pages/activity-page/components/activity-search-bar/activity-search-syntax.tsx, packages/frontend/src/pages/search-page/components/search-bar/search-bar.tsx, packages/frontend/src/pages/search-page/components/search-bar/search-syntax.tsx, packages/frontend/src/pages/search-page/components/search-box/search-box.tsx, packages/frontend/src/pages/search-page/search-page.tsx
Adds popovers to the Insight Search and Activity Search bar, detailing the search syntax.
=> feat: Add search syntax guide popovers to search, activities pages

packages/frontend/src/pages/insight-page/components/insight-viewer/components/insight-comments/components/comment-card/comment-card.tsx, packages/frontend/src/pages/insight-page/components/insight-viewer/components/insight-comments/insight-comments.tsx
Works both on the main InsightViewer, as well as the /discuss subpage
=> feat: Add deeplink to comments on Insights

packages/frontend/src/pages/insight-editor/components/insight-editor-sidebar/sidebar-files.tsx
Chakra UI 1.8.8 updated the `Collapse` component to apply an `overflow: hidden` style, which broke the use of a negative top margin to squash the two components together.
Added a new wrapper element around the `Collapse` to apply the top margin.
=> fix: Fix missing Editor Sidebar icons

packages/frontend/src/components/file-viewer/file-viewer.tsx, packages/frontend/src/components/renderers/json-renderer/json-renderer.tsx, packages/frontend/src/pages/insight-page/components/insight-viewer/insight-viewer.tsx
- Updates the `JSONRenderer` to catch errors trying to convert the JSON into a tabular format to display as a table.  If this happens, it falls back to the original `CodeRenderer`.
- Added properties to `FileViewer` to allow disabling rendered mode--used this to disable the rendered button when viewing the Insight JSON.
=> fix: Allow JSONRenderer to fallback to code view if data is not tabular

packages/backend/schema.gql, packages/backend/src/lib/import.ts, packages/backend/src/resolvers/attachment.resolver.ts, packages/backend/src/resolvers/draft.resolver.ts, packages/backend/src/resolvers/insight.resolver.ts, packages/backend/src/services/draft.service.ts, packages/backend/test/lib/import.test-disabled.ts, packages/frontend/src/pages/insight-editor/insight-draft-container.tsx, packages/frontend/src/pages/insight-editor/insight-draft-editor.tsx, packages/frontend/src/pages/insight-editor/insight-draft-switcher.tsx, packages/frontend/src/pages/insight-editor/insight-editor.tsx
This change contains several commits that migrate the process of creating new Drafts and applying Templates to the backend.  Previously, using a template was a very shallow process whereby the `README.md` contents were copied into the draft via the frontend.  This was limiting in that it didn't allow any additional files to be included in a template.
To address this, the following changes were made:
1. New drafts are created on the backend via a GraphQL mutation.  If the editor loads a new Draft Key that doesn't exist, it triggers a mutation to create the draft and loads it
2. If the user manually changes the template in the Insight Editor, it triggers a GraphQL mutation that applies the draft to the template.  This is similar to the Insight Clone functionality, as it now copies all the …
=> feat: Create Drafts and apply Templates in Backend

packages/frontend/src/components/renderers/table-renderer/table-renderer.tsx, packages/frontend/src/pages/insight-editor/insight-draft-editor.tsx
The recent changes to create new Insight drafts server-side broke the ability to edit an Insight, since there's no logic to initialize a draft from an existing Insight. This fixes the issue by allowing the client-side to create a blank draft and extend it with the contents of the Insight.
=> fix: Fix editing Insight issue caused by server-side drafts

packages/backend/indices/iex-insights.json, packages/backend/schema.gql, packages/backend/src/lib/backends/base.sync.ts, packages/backend/src/lib/backends/file-system.sync.ts, packages/backend/src/lib/backends/github.sync.ts, packages/backend/src/models/insight.ts, packages/backend/src/models/repository.ts, packages/backend/src/resolvers/admin.resolver.ts, packages/backend/src/resolvers/insight.resolver.ts, packages/backend/src/services/comment.service.ts, packages/backend/src/services/insight.service.ts, packages/frontend/src/pages/search-page/components/search-bar/search-bar.tsx, packages/frontend/src/shared/useInsight.ts, packages/frontend/src/shared/useSearch.ts, packages/frontend/src/store/search.slice.ts, packages/models/src/indexed/indexed-insight.ts, packages/models/src/indexed/indexed-repository.ts
Adds three new Insight search options: views, comments, and likes.  A new field for each of these three metrics has been added to Elasticsearch.  Syncing an Insight will recalculate all three; in the meantime each related activity will increment/decrement the corresponding counter.
=> feat: Add Insight search sort options for view/like/comment count

packages/backend/src/lib/backends/github.sync.ts, packages/models/src/indexed/indexed-insight-collaborator.ts
Avoids issues with invalid users not matching the detected schema
=> fix: Limit the collaborator fields stored in Elasticsearch

package-lock.json, packages/frontend/package.json, packages/frontend/src/components/file-viewer/file-viewer.tsx, packages/frontend/src/components/markdown-container/chakra-ui-renderer.tsx, packages/frontend/src/components/renderers/code-renderer/code-renderer-async.tsx, packages/frontend/src/components/renderers/code-renderer/code-renderer.tsx, packages/frontend/src/components/renderers/code-renderer/fetch-code-renderer.tsx, packages/frontend/src/components/renderers/json-renderer/json-renderer.tsx, packages/frontend/src/components/renderers/katex-renderer/katex-renderer-async.tsx, packages/frontend/src/components/renderers/xkcd-chart-renderer/xkcd-chart-renderer-async.tsx, packages/frontend/src/pages/help-page/components/integrations-page/integrations-page.tsx, packages/frontend/src/pages/insight-page/components/insight-viewer/components/share-menu/share-menu.tsx, packages/frontend/src/shared/useFetch.ts, packages/frontend/tsconfig.json, packages/frontend/vite.config.ts
Switches from PrismAsyncLight to Prism to fix `[object Object]` issue, but makes CodeRenderer lazy to compensate for bundle size.
Also included a few other minor changes:
- Upgraded Vite and removed the direct dependency on esbuild (included by Vite)
- Optimized `useFetch` to directly initialize with contents if we have them, reducing redraws
- Optimized code renderer to reduce redraws
- Updated charset removal config in Vite
- Alphabetically sorted `tsconfig.json` in `frontend` package
=> feat: Lazy load CodeRenderer with full Prism syntax highlighter

packages/backend/schema.gql, packages/backend/src/models/autocomplete.ts, packages/backend/src/resolvers/autocomplete.resolver.ts, packages/backend/src/services/user.service.ts, packages/frontend/src/pages/search-page/components/filter-sidebar/components/filter-stack/filter-stack.tsx, packages/frontend/src/pages/search-page/components/filter-sidebar/filter-sidebar.tsx, packages/frontend/src/pages/search-page/components/search-bar/search-syntax.tsx, packages/frontend/src/shared/useSearch.ts, packages/shared/src/search.ts, packages/shared/test/search.test.ts
Two changes related to user display names:
* Authors filter shows display names (if available) instead of usernames.  When selected, the `@username` filter is added as before
* Filtering by display name is now possible using new `author:"Full Name"` syntax.
=> feat: Authors filter shows display names for users, search by display name

packages/backend/src/lib/backends/base.sync.ts, packages/backend/src/lib/backends/github.sync.ts, packages/backend/src/lib/backends/github.ts, packages/backend/src/models/backends/github.ts, packages/backend/src/resolvers/insight.resolver.ts, packages/backend/src/services/insight.service.ts, packages/frontend/src/components/insight-collaborators-modal/insight-collaborators-modal.tsx
Currently, IEX only manages direct collaborators, e.g. users added directly to an Insight repository.  Teams and organizational users don't appear in IEX, and cannot be managed by the UI--they must be managed directly in GitHub.
However, this meant that Unlisted Insights don't appear unless you are a direct collaborator on an Insight.  This is not ideal, so this PR makes a change to the Insight sync process to include ALL collaborators (with higher than READ permissions).  These collaborators are synced to Elasticsearch and will be used to determine if an unlisted Insight can be shown.
This PR does not change the Collaborators UI within IEX--it continues to show and manage direct collaborators only.  A direct link has been added to open the Insight's repository access page in GitHub, …
=> feat: Sync all collaborators to allow teams to view unlisted Insights

packages/frontend/src/shared/useActivities.ts, packages/frontend/src/shared/useSearch.ts
Previously, search-as-you-type could result in a scenario where the results displayed didn't match the user's search.  This occurred because of a bug in the `pending.current` logic that delayed subsequent searches and called `fetchMore()` after the pending query completed.  The issue is that `fetchMore()` runs in the closure of the previous search, so it actually just repeated the old search instead of performing a new search with new variables.
This PR addresses this issue by removing the `pending.current` check, firing all requests when they come in.  When requests complete, they are ignored if they are not the most-recently triggered.  Urql doesn't support AbortController, so we can't cancel the in-progress requests.  If necessary, we can increase the debounce delay to reduce load.
The …
=> fix: Ignore old requests in useSearch hook

packages/backend/src/resolvers/attachment.resolver.ts, packages/frontend/src/pages/settings-page/components/profile-settings/profile-settings.tsx
Fixes two issues with attachments:
- uploading files to an Insight was broken by the switch to ES2022
- newly uploaded avatars were not saving correctly
=> fix: Attachment-related issues

packages/frontend/src/pages/search-page/search-page.tsx
Previously, the `search/setSearchResults` Redux action was being continuously dispatched with the same results, forever.
Added `useMemo` to reuse the same results object, preventing the `useEffect` from triggering the dispatch.
Before:
=> fix: Prevent continuously dispatching search/setSearchResults action

packages/frontend/src/pages/insight-page/components/insight-viewer/components/insight-sidebar/insight-sidebar.tsx, packages/frontend/src/theme.ts
Improvements to the Insight Sidebar:
- Showing file type icons like in the editor
- Automatically removing empty sections, e.g. no Authors, no Team
- Moved Files up, and collapse by default to only show 5
=> feat: Insight Sidebar improvements, including file type icons and auto-hiding sections
